spring:
  datasource:
    url: jdbc:mysql://localhost:3306/spring_batch5?createDatabaseIfNotExist=true
    username: nimauser
    password: 1234

  batch:
    jdbc:
      initialize-schema: always

    job:
      enabled: false

